/**
 * Scans public/images/headquarters for stage/item PNGs and writes
 * src/lib/config/generated/hqAssets.generated.ts
 *
 * Usage: npm run sync:hq
 */
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
  HEADQUARTERS_STAGES_BY_PROFESSION,
  type HeadquartersStageDefinition,
} from "../src/lib/config/headquartersStages.catalog";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const publicDir = path.join(root, "public");
const outFile = path.join(root, "src/lib/config/generated/hqAssets.generated.ts");

function diskExists(urlPath: string | null): boolean {
  if (!urlPath) return false;
  return existsSync(path.join(publicDir, urlPath.replace(/^\//, "")));
}

function stageReady(stage: HeadquartersStageDefinition): boolean {
  if (!diskExists(stage.stageImage)) return false;
  if (stage.stage === 0) return true;
  return diskExists(stage.itemImage);
}

const ready: string[] = [];

for (const stages of Object.values(HEADQUARTERS_STAGES_BY_PROFESSION)) {
  for (const stage of stages) {
    if (stageReady(stage)) {
      ready.push(`${stage.profession}:${stage.stage}`);
    }
  }
}

ready.sort((a, b) => a.localeCompare(b, "en", { numeric: true }));

const body = `/**
 * AUTO-GENERATED by \`npm run sync:hq\` — do not edit by hand.
 * Lists profession:stage keys whose item + stage PNGs exist on disk.
 */
export const HQ_READY_ASSET_KEYS: readonly string[] = ${JSON.stringify(ready, null, 2)};

export function isHqAssetReady(profession: string, stage: number): boolean {
  return HQ_READY_ASSET_KEYS.includes(\`\${profession}:\${stage}\`);
}
`;

mkdirSync(path.dirname(outFile), { recursive: true });
writeFileSync(outFile, body, "utf8");

console.log(`sync:hq wrote ${ready.length} ready stage(s): ${ready.join(", ") || "(none)"}`);
console.log(`→ ${path.relative(root, outFile)}`);
